# Generated by Django 3.1.2 on 2020-10-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_covid', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Loginform',
            new_name='Login',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='usename',
            new_name='username',
        ),
    ]
